function Aeroviewer
    hFig = figure('Menubar','none');
    set(hFig,'units','normalized','outerposition',[0 0 1 1],'name','OBR AeroViewer','numbertitle','off' )
    
    size = get(0,'ScreenSize');
    height = size(4);
    width = size(3)/4;
    s = warning('off', 'MATLAB:uitabgroup:OldVersion');
    hTabGroup = uitabgroup('Parent',hFig);
    warning(s);
    hTabs(1) = uitab('Parent',hTabGroup, 'Title','Setup');
    hTabs(2) = uitab('Parent',hTabGroup, 'Title','Images');

    %% Setup Tab

    namebox = uicontrol('Style','edit',...
        'String','Team:Oxford Brookes Racing          Name: Aeroviewer          Version: Alpha 1.0.0          ',...
        'Position',[width 700 width+width 50], ...
        'Parent',hTabs(1));

    txtbox = uicontrol('Style','edit',...
        'String','Description: Select the button with the correct button orientation, for the wanted image location.',...
        'Position',[width 500 width+width 50], ...
        'Parent',hTabs(1));
    
    b(1) = uicontrol('Style','pushbutton', 'String','Row One...', ...
        'Callback',@figureCallBack11,...
        'Position',[width 300 75 30],...
        'Parent',hTabs(1));
    
    b(2) = uicontrol('Style','pushbutton', 'String','Row Two...', ...
        'Callback',@figureCallBack12,...
        'Position',[width 250 75 30],...
        'Parent',hTabs(1));
    
    b(3) = uicontrol('Style','pushbutton', 'String','Row Three...', ...
        'Callback',@figureCallBack13,...
        'Position',[width 200 75 30],...
        'Parent',hTabs(1));
    
    b(4) = uicontrol('Style','pushbutton', 'String','Row One...', ...
        'Callback',@figureCallBack21,...
        'Position',[width+width 300 75 30],...
        'Parent',hTabs(1));
    
    b(5) = uicontrol('Style','pushbutton', 'String','Row Two...', ...
        'Callback',@figureCallBack22,...
        'Position',[width+width 250 75 30],...
        'Parent',hTabs(1));
    
    b(6) = uicontrol('Style','pushbutton', 'String','Row Three...', ...
        'Callback',@figureCallBack23,...
        'Position',[width+width 200 75 30],...
        'Parent',hTabs(1));
    
	b(7) = uicontrol('Style','pushbutton', 'String','Row One...', ...
        'Callback',@figureCallBack31,...
        'Position',[width+width+width 300 75 30],...
        'Parent',hTabs(1));
    
    b(8) = uicontrol('Style','pushbutton', 'String','Row Two...', ...
        'Callback',@figureCallBack32,...
        'Position',[width+width+width 250 75 30],...
        'Parent',hTabs(1));
    
    b(9) = uicontrol('Style','pushbutton', 'String','Row Three...', ...
        'Callback',@figureCallBack33,...
        'Position',[width+width+width 200 75 30],...
        'Parent',hTabs(1));
    
    %% Button Callback's
    function figureCallBack11(source,eventdata)
        [filename, pathname] = uigetfile({'*.jpg;*.tif;*.png;*.gif','All Image Files';...
          '*.*','All Files' },'Image Selection');
        imagePath=strcat(pathname,filename);
        axes('Parent',hTabs(2),'Position',[0.05 0.7 0.275 0.25]);
        imshow(imagePath);
    end
    function figureCallBack12(source,eventdata)
        [filename, pathname] = uigetfile({'*.jpg;*.tif;*.png;*.gif','All Image Files';...
          '*.*','All Files' },'Image Selection');
        imagePath=strcat(pathname,filename);
        axes('Parent',hTabs(2),'Position',[0.05 0.375 0.275 0.25]);
        imshow(imagePath);
    end
    function figureCallBack13(source,eventdata)
        [filename, pathname] = uigetfile({'*.jpg;*.tif;*.png;*.gif','All Image Files';...
          '*.*','All Files' },'Image Selection');
        imagePath=strcat(pathname,filename);
        axes('Parent',hTabs(2),'Position',[0.05 0.05 0.275 0.25]);
        imshow(imagePath);
    end

    function figureCallBack21(source,eventdata)
        [filename, pathname] = uigetfile({'*.jpg;*.tif;*.png;*.gif','All Image Files';...
          '*.*','All Files' },'Image Selection');
        imagePath=strcat(pathname,filename);
        axes('Parent',hTabs(2),'Position',[0.375 0.7 0.275 0.25]);
        imshow(imagePath);
    end
    function figureCallBack22(source,eventdata)
        [filename, pathname] = uigetfile({'*.jpg;*.tif;*.png;*.gif','All Image Files';...
          '*.*','All Files' },'Image Selection');
        imagePath=strcat(pathname,filename);
        axes('Parent',hTabs(2),'Position',[0.375 0.375 0.275 0.25]);
        imshow(imagePath);
    end
    function figureCallBack23(source,eventdata)
        [filename, pathname] = uigetfile({'*.jpg;*.tif;*.png;*.gif','All Image Files';...
          '*.*','All Files' },'Image Selection');
        imagePath=strcat(pathname,filename);
        axes('Parent',hTabs(2),'Position',[0.375 0.05 0.275 0.25]);
        imshow(imagePath);
    end
    function figureCallBack31(source,eventdata)
        [filename, pathname] = uigetfile({'*.jpg;*.tif;*.png;*.gif','All Image Files';...
          '*.*','All Files' },'Image Selection');
        imagePath=strcat(pathname,filename);
        axes('Parent',hTabs(2),'Position',[0.7 0.7 0.275 0.25]);  
        imshow(imagePath);
    end
    function figureCallBack32(source,eventdata)
        [filename, pathname] = uigetfile({'*.jpg;*.tif;*.png;*.gif','All Image Files';...
          '*.*','All Files' },'Image Selection');
        imagePath=strcat(pathname,filename);
        axes('Parent',hTabs(2),'Position',[0.7 0.375 0.275 0.25]);
        imshow(imagePath);
    end
    function figureCallBack33(source,eventdata)
        [filename, pathname] = uigetfile({'*.jpg;*.tif;*.png;*.gif','All Image Files';...
          '*.*','All Files' },'Image Selection');
        imagePath=strcat(pathname,filename);
        axes('Parent',hTabs(2),'Position',[0.7 0.05 0.275 0.25]);
        imshow(imagePath);
    end
end

